name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Download Android SDK
      uses: android-actions/setup-android@v2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: APK
        path: app/build/outputs/apk/debug/app-debug.apk
